services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/1
    command: bundle exec rails s -p 3000 -b 0.0.0.0
