services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/sena_development
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - mongodb
      - redis
#    command: bundle exec bin/dev
    command: tail -f /dev/null

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: