services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mongodb://localhost:27017/sena_development
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - mongodb
#      - redis
#    command: ./bin/dev
    command: tail -f /dev/null
#    command: bundle exec rails s -p 3000 -b 0.0.0.0
    network_mode: host

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: