services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
    command: bundle exec rails s -p 3000 -b 0.0.0.0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: