FROM ruby:3.4.4-slim-bookworm

# Instalar dependencias del sistema necesarias para Debian
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    curl \
    libxml2 \
    libxml2-dev \
    libxslt1-dev \
    xz-utils \
    vim \
    python3 \
    python3-pip \
    python3-venv \
    postgresql-client \
    libpq-dev \
    libyaml-dev \
    zlib1g-dev \
    libssl-dev \
    libreadline-dev \
    cmake \
    ninja-build \
    gfortran \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

# Crear entorno virtual y ajustar PATH
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Instalar dependencias Ruby y Python
RUN pip install transformers
RUN gem install bundler

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos de la aplicación
COPY Gemfile Gemfile.lock ./

# Instalar dependencias de la aplicación
RUN bundle install

# Configuración de Mongoid (si es necesario)
RUN bundle exec rails g mongoid:config

# Copiar el script de entrada y darle permisos de ejecución
COPY bin/docker-entrypoint /app/bin/docker-entrypoint
RUN chmod +x /app/bin/docker-entrypoint

# Copiar el resto de los archivos de la aplicación
COPY . .

# Convertir finales de línea a formato Unix
RUN find . -type f -exec dos2unix {} \;

# Configurar el entorno de Rails para desarrollo
ENV RAILS_ENV development

# Exponer el puerto en el que la aplicación Rails se ejecutará
EXPOSE 3000

# Comando para iniciar el servidor Rails en modo desarrollo
CMD ["sh", "-c", "source /opt/venv/bin/activate && bundle exec rails server -b 0.0.0.0 -p 3000"]
