development:
  clients:
    default:
      uri: mongodb://localhost:27017/sena_development
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: mongodb+srv://kaox:<DB_PASSWORD>@cluster0.mord5x.mongodb.net/sena_production?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5


